# permissions for end users to view awssecretguardians.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awssecretguardian-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-secret-rotation-controller
    app.kubernetes.io/part-of: k8s-secret-rotation-controller
    app.kubernetes.io/managed-by: kustomize
  name: awssecretguardian-viewer-role
rules:
- apiGroups:
  - secretguardian.omerap12.com
  resources:
  - awssecretguardians
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretguardian.omerap12.com
  resources:
  - awssecretguardians/status
  verbs:
  - get
